name: e_commerce_app2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  cloud_firestore: ^5.6.12
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dots_indicator: ^4.0.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_facebook_auth: ^7.1.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  font_awesome_flutter: ^10.9.1
  get_it: ^8.2.0
  google_sign_in: ^6.2.1
  intl: ^0.20.2
  intl_utils: ^2.8.7
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.2.3
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/bold/
    - assets/images/outlined/

  fonts:
    - family: 'Cairo'
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utilies
  filename: app_images.dart
